{% set version = "0.1.4" %}

package:
  name: pymt_rafem
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pymt_rafem/pymt_rafem-{{ version }}.tar.gz
  sha256: 753e2b92d1f01fd0a06782ce54fcd70723758f37210f4607b397ed075d464579

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - rafem

test:
  imports:
    - pymt_rafem

about:
  home: http://github.com/pymt-lab/pymt_rafem
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'PyMT plugin for the RAFEM'
  doc_url: http://github.com/pymt-lab/pymt_rafem
  dev_url: http://github.com/pymt-lab/pymt_rafem

extra:
  recipe-maintainers:
    - mcflugen
