{% set version = "0.1.3" %}

package:
  name: pymt_rafem
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pymt_rafem/pymt_rafem-{{ version }}.tar.gz
  sha256: 56ccb6d15f1c712c7100f98e396ee787b54cc0b576c906fa859e2f95c4e63fda

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - model_metadata
  run:
    - python
    - rafem

test:
  imports:
    - pymt_rafem

about:
  home: http://github.com/pymt-lab/pymt_rafem
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'PyMT plugin for the RAFEM'
  doc_url: http://github.com/pymt-lab/pymt_rafem
  dev_url: http://github.com/pymt-lab/pymt_rafem

extra:
  recipe-maintainers:
    - mcflugen
