travis:
  secure:
    BINSTAR_TOKEN: UEu7vss/wb8qc8U4L/U3oiKzctIgCOgHFti0XczjPSVtjAP0qYPtFyChLpAv6kxNLJ/4HaJPD/UzufPq3k7ST6BK5iNeF5CcYiprFX9cmA2D+mEW1K8vTPHic7fZ/8+Ed+L6GZMH+6/xrcsQ3cG0borVoTZN6T07NAKKo9k7kCW7ClaskDoH3jn44BlbU9kqrop0wklfIDVdW9f2hrbs4h28iZMGdMJSAnO2LZMoRnQfn/iFyj5xRJpHchflhiQI/j6B+4Wepy/VDKU22FTotF0nkrogCyOxX0wFVZc80mDfl3P8rcLVZOSCDbKIXLr/Qk7yt0YEBGA2Q0x0ZQYEbbi/mjRNxiydjbi/grdj2bC8L5sK0hVvNl69+u8JGWSCtW2GSrzngm9S47U2LkeDk+EmPqsYBsSPVoio1W6gEdg3wsulsh5nuHZkhWK8ZaPrySIxjEIGYPc+y8EgrNbdJrYYktS1DjJC/rynrYfHu8a+wBxOIfC+0dn5j4FMSXTa1aaN4fOcP+hpzcASvLdOw2O5J3PVD1zotnRyjegch64yQIl2rXkb9kAYnSjyp+8r0JW12FUPQ/FBajx4AsWATDLZJPQyDAawFL9JOHqn895uybpVg1Q6SSB42xQ+QQDGwMnMJFmjqseIIXlDM1/Xwg7qnBjMo5+M3+g3qxnNTp4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
