travis:
  secure:
    BINSTAR_TOKEN: U4PN3LVR4VQY7OGf7euQtR+gjj9xlo+24cpsLIXVw0LE4fb+J0W9D52S4CPZektZd4QBIBrlJiJutSMiaShYLS269/UfLSNIXK0JYAJD20lrMPMDrLIJhMSqRKBBVX38zhSNvj8/g/nQDxvAx0G4R3+sar/FSlH22FzAGuGrQ+Vrd3gPcugzLk/Lzw2zr4Tclla8qWezj0HjbHZ1H6PQMT3XieCoM/mm3ku7bIfw3dAhc3JWcUnsQzcSM2NbDCV+dd8T03tVekf9dQMY9OlVv5YqHZ80wx60+dBMhf+garn0yoBtx05G7bTsSX8mwsR/ECgo73u5X8s6QErW2hLJjUoN+W0Bh94jHoHSbD08REwfOVuf+qOu9wbyFSGMKV38gB8h4cIV8vU02Rm0PteKQ4SvJ/rxtuauXO2tSbF00UX3BQrl54EsxYtIKqWJ3cBSpi22MrAhDU+R91SCpKEGab3eYlqF28ykAeC4pysVnUKOs6nFAKC6DqutmsDkISVNWGv8PTDBwF2KG99RndsbRDhb5BcYvfs2oi0T3gLLsvCR1B+x5INYGn9BzVyKwFgjaihf/WXJLpmES13Y3CO1LGHDZZg5I6h5odpioxcHg+oXJPrS2HVo6VuTmdnIeMdkCPXrW4dRt1GujwvH2oGH9P3E26q2LoRkr1e8wFTeVKM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
